input_dir: "./input"

http:
  timeout_seconds: 30
  retries: 3
  sources:
    - url: "http://www.compel.ru/stockfiles2/d18753d36a2d519536b91315f457bcb2/"
      filename: "input.dbf"

    - url: "https://ruelectronics.com/upload/catalog.xlsx?1769496427"
      filename: "x4.xlsx"

    - url: "https://www.radioelementy.ru/upload/export/today/a.sotnikov.xlsx"
      filename: "x1.xlsx"

ftp:
  enabled: true
  host: "ftp.itecs.ru"
  port: 21
  user: "tellur"
  password: "uzz$9T6k*6X4My6#^"
  timeout_seconds: 30
  retries: 3
  remote_dir: "."        # текущая директория
